imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: app.yml }
    - { resource: fos.yml }

framework:
    esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    spool:     { type: memory }
    spool:
        type: file
        path: "%kernel.root_dir%/../spool"

knp_time: ~

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [AppBackendBundle]
        directories: ["%kernel.root_dir%/../src"]

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        avatarTiny:
            quality: 100
            filters:
                thumbnail: { size: [75,75], mode: outbound }
        avatarBig:
            quality: 100
            filters:
                thumbnail: { size: [150,150], mode: outbound }
        tiny:
            quality: 100
            filters:
                thumbnail: { size: [50,50], mode: outbound }
        lessonPreview:
            quality: 100
            filters:
                thumbnail: { size: [267,178], mode: outbound }
        chapter:
            quality: 100
            filters:
                thumbnail: { size: [120,90], mode: outbound }
        uploadPreview:
           quality: 100
           filters:
                thumbnail: { size: [120,92], mode: outbound }
        lessonTiny:
            quality: 100
            filters:
                thumbnail: { size: [100,100], mode: outbound }
knp_time: ~
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

app_backend:
    notify_email: service@symfonytutorial.com
#    alipay:
#        pid: 2088112046306645
#        key: hccm38c03lsu819dze4oxrpfxu9qz35n