parameters:
#    app_frontend.example.class: App\FrontendBundle\Example

services:
    event_subscriber.login_redirect:
        class: App\FrontendBundle\EventListener\RedirectAfterLogin
        tags:
            - { name: kernel.event_subscriber }