parameters:


services:
    #Twig
    bool.twig.extension:
        class: App\BackendBundle\TwigExtension\PageBoolExtension
        tags:
            - { name: twig.extension }
    format.twig.extension:
        class: App\BackendBundle\TwigExtension\FormatExtension
        tags:
            - { name: twig.extension }
    #File Upload
    file.upload:
        class: App\BackendBundle\Upload\FileUpload
        arguments: [@service_container]

    #Entity
    lesson.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\Lesson ]

    chapter.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\Chapter ]

    category.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\Category ]

    user.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\User ]