parameters:


services:
    #Twig
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    bool.twig.extension:
        class: App\BackendBundle\TwigExtension\PageBoolExtension
        tags:
            - { name: twig.extension }
    format.twig.extension:
        class: App\BackendBundle\TwigExtension\FormatExtension
        tags:
            - { name: twig.extension }
    #File Upload
    file.upload:
        class: App\BackendBundle\Upload\FileUpload
        arguments: [@service_container]

    #Entity
    lesson.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\Lesson ]

    chapter.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\Chapter ]

    category.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\Category ]

    user.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\User ]

    purchase.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\Purchase ]

    thread.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\Thread ]

    reply.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\Reply ]

    alipay.entity:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ App\BackendBundle\Entity\Alipay ]
    #pagination
    thread.paginator:
        class: App\BackendBundle\Pagination\KnpPagination
        arguments: [ @knp_paginator , @thread.entity , @request_stack ]

    reply.paginator:
        class: App\BackendBundle\Pagination\KnpPagination
        arguments: [ @knp_paginator , @reply.entity , @request_stack ]